@startuml
'default
top to bottom direction
(sign in initiate) --> (work at home): Home
(sign in initiate) --> (work at office): Office
(sign in initiate) --> (on business trip): Business Trip
(sign in initiate) --> (check rewrite): Rewrite the log
(sign in initiate) --> (cancel): Cancel
(sign in initiate) --> (Ask reason): Yes. I text you the reason
(work at home) --> (location): location
(work at home) --> (location Not available): Not Available
(location) --> (confirmation): Confirm
(location) --> (Go back): Go back
(location) --> (Report content): Send content of today
(location) --> (Go back): Go back
(confirmation) --> (location is changed): Explain The location difference
(confirmation) --> (location): location
(location is changed) --> (get explain): get text
(get explain) --> (end): Confirm
(get explain) --> (location is changed): Explain The location difference
(Go back) --> (work at home): Home
(Go back) --> (work at office): Office
(Go back) --> (on business trip): Business Trip
(work at office) --> (location): location
(work at office) --> (location Not available): Not Available
(location Not available) --> (confirmation): Confirm
(location Not available) --> (Go back): Go back
(location Not available) --> (Report content): Send content of today
(location Not available) --> (Go back): Go back
(Report content) --> (receve content): text
(receve content) --> (save content): Save content
(receve content) --> (edit content): Edit content
(save content) --> (confirmation): Confirm
(save content) --> (Go back): Go back
(edit content) --> (confirmation): Confirm
(edit content) --> (Go back): Go back
(on business trip) --> (location): location
(on business trip) --> (location Not available): Not Available
(check rewrite) --> (confirm rewrite): Yes, I delete and write again
(check rewrite) --> (cancel): Cancel
(confirm rewrite) --> (work at home): Home
(confirm rewrite) --> (work at office): Office
(confirm rewrite) --> (on business trip): Business Trip
(Ask reason) --> (Receved reason): text
(Receved reason) --> (work at home): Home
(Receved reason) --> (work at office): Office
(Receved reason) --> (on business trip): Business Trip
@enduml