@startuml
'default
top to bottom direction
(getting back) --> (lunch_with_koica): With KOICA Colleagues
(getting back) --> (lunch wihtout koica): Without any member of KOICA
(getting back) --> (check rewrite lunch log): Rewrite the lunch log
(getting back) --> (cancel): Cancel
(lunch_with_koica) --> (location): location
(lunch_with_koica) --> (location Not available): Not Available
(location) --> (confirmation): Confirm
(location) --> (Go back): Go_back
(Go back) --> (lunch_with_koica): With KOICA Colleagues
(Go back) --> (lunch wihtout koica): Without any member of KOICA
(lunch wihtout koica) --> (location): location
(lunch wihtout koica) --> (location Not available): Not Available
(location Not available) --> (confirmation): Confirm
(location Not available) --> (Go back): Go_back
(check rewrite lunch log) --> (confirm rewrite): Yes, I delete and write again
(check rewrite lunch log) --> (cancel): Cancel
(confirm rewrite) --> (lunch_with_koica): With KOICA Colleagues
(confirm rewrite) --> (lunch wihtout koica): Without any member of KOICA
@enduml